CREATE SEQUENCE patrimonio_id_seq START 1;

CREATE TABLE LOCALIZACAO (
    ID NUMERIC AUTO_INCREMENT PRIMARY KEY,
    LOGRADOURO TEXT NOT NULL,
    NUMERO NUMERIC,
    UF TEXT NOT NULL,
    CIDADE TEXT NOT NULL,
    SETOR TEXT NOT NULL,
    CEP TEXT NOT NULL,
    COMPLEMENTO TEXT
);

CREATE TABLE PATRIMONIO(
    ID NUMERIC PRIMARY KEY NOT NULL DEFAULT nextval('patrimonio_id_seq'),
    NOME TEXT NOT NULL,
    CODIGO TEXT NOT NULL,
    TIPO TEXT NOT NULL,
    ESTADO TEXT NOT NULL,
    RESPONSAVEL_ATUAL TEXT NOT NULL,
    DATA_AQUISICAO DATE NOT NULL
    FK_LOCALIZACAO NUMERIC NOT NULL,

    CONSTRAINT FK_LOCALIZACAO_PATRIMONIO FOREIGN KEY (FK_LOCALIZACAO) REFERENCES LOCALIZACAO(ID)
);